### ISSUE TITLE
Proposal to choose a more portable language

### ISSUE THREAD

**Issue by CooCooCaCha** [PathOfBuildingCommunity/PathOfBuilding-Python#18]
Hey, first of all cool project! I was thinking recently about what a new version of PoB could look like and it brought me here. 

I was thinking it'd be a good idea to build the core (non-GUI) code in a more portable language. Namely Rust. Since rust is compiled and has no garbage collector it can be used in a wider variety of places and is compatible with other programming languages.

For example, you could compile rust into a WASM module and load it in a web version of PoB. You could compile it as a native python [1] module or really any language that supports importing compiled libraries. 

It would be amazing for the community if we had a solid, portable library for performing path of exile calculations that could be used in a maximum number of projects.

[1] https://github.com/PyO3/pyo3

**Comment by drsaeva** [comment]
I have little Rust capabilities myself (currently), but I too think this is a good idea. Just stumbled on this project and wanted to add that I've been wishing for a while for a browser-native version of PoB that is performant and up to modern web standards (read - not a port of the Lua engine running in the browser).

A Rust core for handling some of the heavier lifting might be a good idea, though it also might be ultimately unnecessary depending on the weight of some components.

**Comment by ppoelzl** [comment]
First and foremost, Path of Building is intended as a desktop application. While there are efforts to separate the frontend and backend, bringing Path of Building to the web is not currently a goal in this project. If you still wanted to compile the backend library to WebAssembly, there might be a way. See https://github.com/pyodide/pyodide

On Rust: It's a fine language. I've worked with PyO3 before and if we ever need to reach for native modules, Rust will be our language of choice. However, it also comes with a steep learning curve, and currently there is very litte Rust mindshare in our community. So at least in our case, it is not fit for implementing the whole calculation engine in it.
