### ISSUE TITLE
In regards to Contributions

### ISSUE THREAD

**Issue by svrNinety** [PathOfBuildingCommunity/PathOfBuilding-Python#4]
Hey there,

I saw you guys recently started working on a Python port of PoB. I'd be highly interested to contribute in this undertaking. 

> Pull requests are welcome! This project is in its very early stages, so there are plenty of opportunities to contribute.

Is there a developer discord, mail list, skype group or any other platform you guys use for syncing up?

Greetings,
sVr

**Comment by washa3** [comment]
@svrNinety @kmoulins  there is an official discord server which can be found in PoBC's github page 

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CONTRIBUTING.md

**Comment by svrNinety** [comment]
Ty @washa3. Closed Issue.
