### ISSUE TITLE
Is this project meant to replace only the lua part or also the launcher and gui?

### ISSUE THREAD

**Issue by kmoulins** [PathOfBuildingCommunity/PathOfBuilding-Python#5]
Will this merge the lua, launcher and simple graphics dll into a single 100% python project or are the last two staying more or less as is?

**Comment by ppoelzl** [comment]
The first step is to establish a calculation engine, the second is a new frontend based on Qt. This project will be mostly Python, but probably incorporate some other more low level language as well, most likely Rust.
